libDir    = '/usr/local/cuda/lib64';
structDir = '../src';

% ---

files = ...
{
'../src/BFGS.cu', ...
'../src/assignStructMemory.cu', ...
'../src/updateInverseHessian.cu', ...
'../src/lineSearch.cu', ...
'runBFGS.cu', ...
'bealeFunction.cu', ...
};

mexcuda(['-L', libDir], ['-I', structDir], files, '-lcublas', '-output', 'BFGS_beale');

% ---

files = ...
{
'../src/BFGS.cu', ...
'../src/assignStructMemory.cu', ...
'../src/updateInverseHessian.cu', ...
'../src/lineSearch.cu', ...
'runBFGS.cu', ...
'rosenbrockFunction.cu', ...
};

mexcuda(['-L', libDir], ['-I', structDir], files, '-lcublas', '-output', 'BFGS_rosenbrock');
