function [fcnVal, grdVec] = bealeFunction(posVec)

if length(posVec) ~= 2
	error('BEALEFUNCTION only works for dimension 2.');
end

% minimum  : 0
% minimizer: (3, 0.5)

xVal = posVec(1);
yVal = posVec(2);

fcnVal =  (1.5   - xVal + xVal * yVal  )^2 ...
        + (2.25  - xVal + xVal * yVal^2)^2 ...
        + (2.625 - xVal + xVal * yVal^3)^2;

grdVec = [  2 * (1.5   - xVal + xVal * yVal  ) * (-1 + yVal  )  ...
          + 2 * (2.25  - xVal + xVal * yVal^2) * (-1 + yVal^2)  ...
          + 2 * (2.625 - xVal + xVal * yVal^3) * (-1 + yVal^3); ...
            2 * (1.5   - xVal + xVal * yVal  ) *     xVal        ...
          + 2 * (2.25  - xVal + xVal * yVal^2) * 2 * xVal * yVal ...
          + 2 * (2.625 - xVal + xVal * yVal^3) * 3 * xVal * yVal^2];
